language: cpp
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libopencv-dev
script:
  - cmake -Duse_own_opencv=no .
  - make -j4
  - python ./bin/unit_tests
  - ./build/lint_all.py

